// <auto-generated />
using System;
using System.Collections.Generic;
using AISupportOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AISupportOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008141346_AddEvaluationAndFeedback")]
    partial class AddEvaluationAndFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AISupportOps.Domain.Agents.ToolExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arguments_json");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tool_executions");

                    b.HasIndex("TenantId", "RunId")
                        .HasDatabaseName("ix_tool_executions_tenant_id_run_id");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_tool_executions_tenant_id_status_created_at");

                    b.HasIndex("TenantId", "ToolName", "CreatedAt")
                        .HasDatabaseName("ix_tool_executions_tenant_id_tool_name_created_at");

                    b.ToTable("tool_executions", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_created_at");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_entity_type_entity_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Chat.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<DateTimeOffset?>("SummarizedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summarized_until");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversations_user_id");

                    b.HasIndex("TenantId", "UserId", "LastMessageAt")
                        .HasDatabaseName("ix_conversations_tenant_id_user_id_last_message_at");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Chat.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FeedbackAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_at");

                    b.Property<string>("FeedbackComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("feedback_comment");

                    b.Property<bool?>("FeedbackHelpful")
                        .HasColumnType("boolean")
                        .HasColumnName("feedback_helpful");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<long?>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_id");

                    b.Property<string>("RetrievalQuery")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("retrieval_query");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.HasIndex("TenantId", "ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_messages_tenant_id_conversation_id_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_count");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("processing_attempts");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_documents_storage_key");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_documents_uploaded_by_user_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_documents_tenant_id_created_at");

                    b.HasIndex("TenantId", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("ix_documents_tenant_id_sha256");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_documents_tenant_id_status");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Documents.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Heading")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("heading");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_chunks");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_chunks_document_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_document_chunks_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("TenantId", "DocumentId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_document_chunks_tenant_id_document_id_index");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Evaluation.EvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AbstentionCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("abstention_correct");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("case_id");

                    b.Property<bool?>("CitedExpectedSource")
                        .HasColumnType("boolean")
                        .HasColumnName("cited_expected_source");

                    b.PrimitiveCollection<List<string>>("CitedSources")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cited_sources");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpectedSource")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("expected_source");

                    b.Property<int?>("ExpectedSourceRank")
                        .HasColumnType("integer")
                        .HasColumnName("expected_source_rank");

                    b.Property<double?>("Groundedness")
                        .HasColumnType("double precision")
                        .HasColumnName("groundedness");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("JudgeNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("judge_notes");

                    b.Property<double?>("KeyFactCoverage")
                        .HasColumnType("double precision")
                        .HasColumnName("key_fact_coverage");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.PrimitiveCollection<List<string>>("MissingKeyFacts")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("missing_key_facts");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.PrimitiveCollection<List<string>>("RetrievedSources")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("retrieved_sources");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<bool>("ShouldAbstain")
                        .HasColumnType("boolean")
                        .HasColumnName("should_abstain");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_evaluation_results");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_evaluation_results_run_id");

                    b.HasIndex("TenantId", "RunId")
                        .HasDatabaseName("ix_evaluation_results_tenant_id_run_id");

                    b.ToTable("evaluation_results", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Evaluation.EvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChatModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chat_model");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_id");

                    b.Property<Guid>("StartedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UsedJudge")
                        .HasColumnType("boolean")
                        .HasColumnName("used_judge");

                    b.HasKey("Id")
                        .HasName("pk_evaluation_runs");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_evaluation_runs_tenant_id_created_at");

                    b.ToTable("evaluation_runs", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("ix_refresh_tokens_user_id_tenant_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Tenants.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_invitations_invited_by_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token_hash");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .HasDatabaseName("ix_invitations_tenant_id_normalized_email");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Tenants.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_memberships_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_memberships_tenant_id_user_id");

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Tickets.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_customers_tenant_id_name");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_tenant_id_normalized_email");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Tickets.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_support_tickets");

                    b.HasIndex("AssigneeUserId")
                        .HasDatabaseName("ix_support_tickets_assignee_user_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_support_tickets_created_by_user_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_support_tickets_customer_id");

                    b.HasIndex("TenantId", "CustomerId")
                        .HasDatabaseName("ix_support_tickets_tenant_id_customer_id");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_support_tickets_tenant_id_number");

                    b.HasIndex("TenantId", "AssigneeUserId", "Status")
                        .HasDatabaseName("ix_support_tickets_tenant_id_assignee_user_id_status");

                    b.HasIndex("TenantId", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_support_tickets_tenant_id_status_updated_at");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Infrastructure.Persistence.Configurations.TicketCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.HasKey("TenantId")
                        .HasName("pk_ticket_counters");

                    b.ToTable("ticket_counters", (string)null);
                });

            modelBuilder.Entity("AISupportOps.Domain.Agents.ToolExecution", b =>
                {
                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tool_executions_tenants_tenant_id");
                });

            modelBuilder.Entity("AISupportOps.Domain.Auditing.AuditLog", b =>
                {
                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_tenants_tenant_id");

                    b.OwnsMany("AISupportOps.Domain.Auditing.AuditChange", "Changes", b1 =>
                        {
                            b1.Property<Guid>("AuditLogId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Field")
                                .IsRequired();

                            b1.Property<string>("From");

                            b1.Property<string>("To");

                            b1.HasKey("AuditLogId", "__synthesizedOrdinal");

                            b1.ToTable("audit_logs");

                            b1
                                .ToJson("changes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AuditLogId")
                                .HasConstraintName("fk_audit_logs_audit_logs_audit_log_id");
                        });

                    b.Navigation("Changes");
                });

            modelBuilder.Entity("AISupportOps.Domain.Chat.Conversation", b =>
                {
                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_tenants_tenant_id");

                    b.HasOne("AISupportOps.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_user_id");
                });

            modelBuilder.Entity("AISupportOps.Domain.Chat.Message", b =>
                {
                    b.HasOne("AISupportOps.Domain.Chat.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.OwnsMany("AISupportOps.Domain.Chat.MessageCitation", "Citations", b1 =>
                        {
                            b1.Property<Guid>("MessageId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("DocumentId");

                            b1.Property<string>("FileName")
                                .IsRequired();

                            b1.Property<string>("Heading");

                            b1.Property<int>("Number");

                            b1.Property<int?>("PageNumber");

                            b1.Property<double>("Score");

                            b1.Property<string>("Snippet")
                                .IsRequired();

                            b1.HasKey("MessageId", "__synthesizedOrdinal");

                            b1.ToTable("messages");

                            b1
                                .ToJson("citations")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MessageId")
                                .HasConstraintName("fk_messages_messages_message_id");
                        });

                    b.Navigation("Citations");
                });

            modelBuilder.Entity("AISupportOps.Domain.Documents.Document", b =>
                {
                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_tenants_tenant_id");

                    b.HasOne("AISupportOps.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("AISupportOps.Domain.Documents.DocumentChunk", b =>
                {
                    b.HasOne("AISupportOps.Domain.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_chunks_documents_document_id");
                });

            modelBuilder.Entity("AISupportOps.Domain.Evaluation.EvaluationResult", b =>
                {
                    b.HasOne("AISupportOps.Domain.Evaluation.EvaluationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evaluation_results_evaluation_runs_run_id");
                });

            modelBuilder.Entity("AISupportOps.Domain.Evaluation.EvaluationRun", b =>
                {
                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evaluation_runs_tenants_tenant_id");

                    b.OwnsOne("AISupportOps.Domain.Evaluation.EvaluationSummary", "Summary", b1 =>
                        {
                            b1.Property<Guid>("EvaluationRunId");

                            b1.Property<double?>("AbstentionAccuracy");

                            b1.Property<double?>("AnswerRate");

                            b1.Property<double>("AverageLatencyMs");

                            b1.Property<int>("CaseCount");

                            b1.Property<double?>("CitationAccuracy");

                            b1.Property<double?>("Groundedness");

                            b1.Property<long>("InputTokens");

                            b1.Property<double?>("KeyFactCoverage");

                            b1.Property<double?>("MeanReciprocalRank");

                            b1.Property<long>("OutputTokens");

                            b1.Property<double?>("RetrievalHitRate");

                            b1.HasKey("EvaluationRunId");

                            b1.ToTable("evaluation_runs");

                            b1
                                .ToJson("summary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EvaluationRunId")
                                .HasConstraintName("fk_evaluation_runs_evaluation_runs_id");
                        });

                    b.Navigation("Summary")
                        .IsRequired();
                });

            modelBuilder.Entity("AISupportOps.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("AISupportOps.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("AISupportOps.Domain.Tenants.Invitation", b =>
                {
                    b.HasOne("AISupportOps.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_users_invited_by_user_id");

                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_tenants_tenant_id");
                });

            modelBuilder.Entity("AISupportOps.Domain.Tenants.TenantMembership", b =>
                {
                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                    b.HasOne("AISupportOps.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISupportOps.Domain.Tickets.Customer", b =>
                {
                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_tenants_tenant_id");
                });

            modelBuilder.Entity("AISupportOps.Domain.Tickets.SupportTicket", b =>
                {
                    b.HasOne("AISupportOps.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_support_tickets_users_assignee_user_id");

                    b.HasOne("AISupportOps.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_support_tickets_users_created_by_user_id");

                    b.HasOne("AISupportOps.Domain.Tickets.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_support_tickets_customers_customer_id");

                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_tickets_tenants_tenant_id");
                });

            modelBuilder.Entity("AISupportOps.Infrastructure.Persistence.Configurations.TicketCounter", b =>
                {
                    b.HasOne("AISupportOps.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_counters_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
