namespace AISupportOps.Application.Documents;

/// <summary>
/// Blob storage for document bytes. Keys are generated by the system
/// (never derived from user input), e.g. "{tenantId}/{documentId}".
/// Implementations: local disk (development), Azure Blob Storage (production).
/// </summary>
public interface IFileStorage
{
    Task SaveAsync(string key, Stream content, CancellationToken ct);

    Task<Stream> OpenReadAsync(string key, CancellationToken ct);

    Task DeleteAsync(string key, CancellationToken ct);
}
